# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFZmv42PuSqenABZGHohGupaRInyht5Y
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([3,5,9,7,9])
y=np.array([33,26,15,45,9])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([7,9,1,6,3])

plt.plot(x,marker='+')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,6,9,7])

plt.plot(y,marker='*',ms=60)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([9,4,6,1])

plt.plot(y,marker='*',ms=30,mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([9,4,6,1])

plt.plot(y,marker='*',ms=30,mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,4,9,1,3])
y=np.array([9,4,6,1,5,7,11])

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,4,9,1,3])
y=np.array([9,4,6,1,5,7,11])
plt.scatter(x,y,color='red')

x=np.array([4,6,8,2])
y=np.array([1,3,5,7])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,3])
y=np.array([9,4,6,11])
mycolor=['red','green','purple','lime']

plt.scatter(x,y,color=mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,3])
y=np.array([9,4,6,11])
mycolor=['red','green','purple','lime']
size=[30,100,150,200]

plt.scatter(x,y,color=mycolor,s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([613,510,614])
y=np.array([20,18,23])
plt.bar(x,y)



plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([90,50,42,10])


plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([90,50,42,10])
mylabels=["Mexriniso","Asomiddin","Xalima"]


plt.pie(y,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([90,50,42,10])
mylabels=["Mexriniso","Asomiddin","Xalima"]
myexplode=[0.2,0,0]


plt.pie(y,labels=mylabels,
        startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([90,50,42,10])
mylabels=["Mexriniso","Asomiddin","Xalima"]
mycolors=["black","hotpink","r","y"]
myexplode=[0.2,0,0]


plt.pie(y,labels=mylabels,
startangle=90,explode=myexplode,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([90,50,42,10])
mylabels=["Mexriniso","Asomiddin","Xalima"]
mycolors=["black","hotpink","r","y"]
myexplode=[0.2,0,0]


plt.pie(y,labels=mylabels)
plt.legend(title='Ismlar')
plt.show()